/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Sponsor = {
	_id: string;
	_type: 'sponsor';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	since: string;
	tier: 'gold' | 'silver' | 'special';
	name: string;
	logo: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		_type: 'image';
	};
	logoDark?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	note?: string;
};

export type Info = {
	_id: string;
	_type: 'info';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	email: string;
	socials?: Array<{
		platform: string;
		link: string;
		_key: string;
	}>;
};

export type Board = {
	_id: string;
	_type: 'board';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	year: number;
	sections: Array<{
		label: string;
		members: Array<{
			title: string;
			terms?: Array<string>;
			person: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'person';
			};
			_type: 'member';
			_key: string;
		}>;
		_type: 'section';
		_key: string;
	}>;
};

export type Person = {
	_id: string;
	_type: 'person';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name: string;
	slug: Slug;
	pronouns?: Array<string>;
	email?: string;
	discord?: string;
	website?: string;
	linkedin?: string;
	instagram?: string;
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	majors?: Array<string>;
	graduation: number;
};

export type Resource = {
	_id: string;
	_type: 'resource';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	description: string;
	notes?: string;
	category?: 'tool' | 'guide' | 'certification' | 'other';
	link?: string;
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		_type: 'image';
	};
	tags?: Array<string>;
};

export type ContactPage = {
	_id: string;
	_type: 'contactPage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	sections?: Array<{
		title: string;
		description: string;
		contacts?: Array<{
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			_key: string;
			[internalGroqTypeReferenceTo]?: 'person';
		}>;
		_type: 'section';
		_key: string;
	}>;
};

export type SubteamsPage = {
	_id: string;
	_type: 'subteamsPage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	subteams?: Array<{
		name?: string;
		description?: string;
		_type: 'subteam';
		_key: string;
	}>;
};

export type Achievements = {
	_type: 'achievements';
	years?: Array<{
		year?: number;
		achievements?: Array<{
			title?: string;
			placing?: string;
			_type: 'achievement';
			_key: string;
		}>;
		_type: 'year';
		_key: string;
	}>;
};

export type CompetitionPage = {
	_id: string;
	_type: 'competitionPage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	content?: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?: 'normal' | 'h2' | 'h3';
				listItem?: never;
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| ({
				_key: string;
		  } & Achievements)
	>;
};

export type HomePage = {
	_id: string;
	_type: 'homePage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	highlightNews?: {
		enable?: boolean;
		article?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'news';
		};
	};
	competitions: {
		subtitle: string;
		description: string;
	};
	hackerlab: {
		images: Array<{
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
			};
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt: string;
			_type: 'image';
			_key: string;
		}>;
		description: string;
	};
};

export type News = {
	_id: string;
	_type: 'news';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	date: string;
	title: string;
	slug: Slug;
	cover: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	content: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: 'span';
			_key: string;
		}>;
		style?: 'normal' | 'h2' | 'h3';
		listItem?: never;
		markDefs?: Array<{
			href?: string;
			_type: 'link';
			_key: string;
		}>;
		level?: number;
		_type: 'block';
		_key: string;
	}>;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type Slug = {
	_type: 'slug';
	current: string;
	source?: string;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type AllSanitySchemaTypes =
	| Sponsor
	| Info
	| Board
	| Person
	| Resource
	| ContactPage
	| SubteamsPage
	| Achievements
	| CompetitionPage
	| HomePage
	| News
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageHotspot
	| SanityImageCrop
	| SanityFileAsset
	| SanityImageAsset
	| SanityImageMetadata
	| Geopoint
	| Slug
	| SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/routes/(homepage)/+page.server.ts
// Variable: homePageQuery
// Query: *[_type == 'homePage' && _id == "homePage"][0] {			highlightNews {				enable,				article -> {					title,					cover,					date,					slug,				},			},			competitions {				subtitle,				description,			},			hackerlab {				description,				images,			},		}
export type HomePageQueryResult = {
	highlightNews: {
		enable: boolean | null;
		article: {
			title: string;
			cover: {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
			};
			date: string;
			slug: Slug;
		} | null;
	} | null;
	competitions: {
		subtitle: string;
		description: string;
	};
	hackerlab: {
		description: string;
		images: Array<{
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
			};
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt: string;
			_type: 'image';
			_key: string;
		}>;
	};
} | null;
// Variable: socialsQuery
// Query: *[_type == 'info' && _id == "info"][0] {			socials		}
export type SocialsQueryResult = {
	socials: Array<{
		platform: string;
		link: string;
		_key: string;
	}> | null;
} | null;

// Source: ./src/routes/aif/+page.server.ts
// Variable: aifSocialsQuery
// Query: *[_type == 'info' && _id == "info"][0] {			socials		}
export type AifSocialsQueryResult = {
	socials: Array<{
		platform: string;
		link: string;
		_key: string;
	}> | null;
} | null;

// Source: ./src/routes/board/+page.server.ts
// Variable: boardPageQuery
// Query: *[_type == "board"] | order(year desc) {			_id,			year,			sections[] {				_key,				label,				"members": members[].person-> {					"person": @,					"titles": ^.members[person._ref match ^._id].title				} 			}		}
export type BoardPageQueryResult = Array<{
	_id: string;
	year: number;
	sections: Array<{
		_key: string;
		label: string;
		members: Array<{
			person: {
				_id: string;
				_type: 'person';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				name: string;
				slug: Slug;
				pronouns?: Array<string>;
				email?: string;
				discord?: string;
				website?: string;
				linkedin?: string;
				instagram?: string;
				image?: {
					asset?: {
						_ref: string;
						_type: 'reference';
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
					};
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				};
				majors?: Array<string>;
				graduation: number;
			};
			titles: Array<string>;
		}>;
	}>;
}>;

// Source: ./src/routes/competition/+page.server.ts
// Variable: competitionPageQuery
// Query: *[_type == "competitionPage"][0] {			content		}
export type CompetitionPageQueryResult = {
	content: Array<
		| ({
				_key: string;
		  } & Achievements)
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?: 'h2' | 'h3' | 'normal';
				listItem?: never;
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
	> | null;
} | null;

// Source: ./src/routes/contact/+page.server.ts
// Variable: contactPageQuery
// Query: *[_type == "contactPage"][0] {			sections[] {				_key,				title,				description,				contacts[]-> {					_id,					image,					name,					pronouns,					email,					"titles": *[_type == "board"] | order(year desc)[0].sections[].members[person._ref match ^._id].title				}			}		}
export type ContactPageQueryResult = {
	sections: Array<{
		_key: string;
		title: string;
		description: string;
		contacts: Array<{
			_id: string;
			image: {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
			} | null;
			name: string;
			pronouns: Array<string> | null;
			email: string | null;
			titles: Array<string> | null;
		}> | null;
	}> | null;
} | null;

// Source: ./src/routes/news/+page.server.ts
// Variable: newsPageQuery
// Query: *[_type == "news"] | order(date desc) {			_id,			title,			slug,			date,			cover,		}
export type NewsPageQueryResult = Array<{
	_id: string;
	title: string;
	slug: Slug;
	date: string;
	cover: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
}>;

// Source: ./src/routes/news/[slug]/+page.server.ts
// Variable: newsStoryPageQuery
// Query: *[_type == "news" && slug.current == $slug][0] {			content,			title		}
export type NewsStoryPageQueryResult = {
	content: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: 'span';
			_key: string;
		}>;
		style?: 'h2' | 'h3' | 'normal';
		listItem?: never;
		markDefs?: Array<{
			href?: string;
			_type: 'link';
			_key: string;
		}>;
		level?: number;
		_type: 'block';
		_key: string;
	}>;
	title: string;
} | null;

// Source: ./src/routes/resources/+page.server.ts
// Variable: resourcesQuery
// Query: *[_type == "resource"] {      _id,      title,      description,      notes,      category,      link,      image {        asset->{          url        },        alt      },      tags    }
export type ResourcesQueryResult = Array<{
	_id: string;
	title: string;
	description: string;
	notes: string | null;
	category: 'certification' | 'guide' | 'other' | 'tool' | null;
	link: string | null;
	image: {
		asset: {
			url: string | null;
		} | null;
		alt: string;
	} | null;
	tags: Array<string> | null;
}>;

// Source: ./src/routes/sponsors/+page.server.ts
// Variable: sponsorQuery
// Query: *[_type == "sponsor"] {			_id,			since,			tier,			name,			logo {				asset->{					url				},				alt			},			logoDark {				asset->{					url				}			},			note		}
export type SponsorQueryResult = Array<{
	_id: string;
	since: string;
	tier: 'gold' | 'silver' | 'special';
	name: string;
	logo: {
		asset: {
			url: string | null;
		} | null;
		alt: string;
	};
	logoDark: {
		asset: {
			url: string | null;
		} | null;
	} | null;
	note: string | null;
}>;

// Source: ./src/routes/subteams/+page.server.ts
// Variable: subteamPageQuery
// Query: *[_type == "subteamsPage"][0] {			_id,			subteams[] {				_key,				name,				description			}		}
export type SubteamPageQueryResult = {
	_id: string;
	subteams: Array<{
		_key: string;
		name: string | null;
		description: string | null;
	}> | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
	interface SanityQueries {
		'\n\t\t*[_type == \'homePage\' && _id == "homePage"][0] {\n\t\t\thighlightNews {\n\t\t\t\tenable,\n\t\t\t\tarticle -> {\n\t\t\t\t\ttitle,\n\t\t\t\t\tcover,\n\t\t\t\t\tdate,\n\t\t\t\t\tslug,\n\t\t\t\t},\n\t\t\t},\n\t\t\tcompetitions {\n\t\t\t\tsubtitle,\n\t\t\t\tdescription,\n\t\t\t},\n\t\t\thackerlab {\n\t\t\t\tdescription,\n\t\t\t\timages,\n\t\t\t},\n\t\t}\n  ': HomePageQueryResult;
		'\n\t\t*[_type == \'info\' && _id == "info"][0] {\n\t\t\tsocials\n\t\t}\n\t':
			| SocialsQueryResult
			| AifSocialsQueryResult;
		'\n\t\t*[_type == "board"] | order(year desc) {\n\t\t\t_id,\n\t\t\tyear,\n\t\t\tsections[] {\n\t\t\t\t_key,\n\t\t\t\tlabel,\n\t\t\t\t"members": members[].person-> {\n\t\t\t\t\t"person": @,\n\t\t\t\t\t"titles": ^.members[person._ref match ^._id].title\n\t\t\t\t} \n\t\t\t}\n\t\t}\n  ': BoardPageQueryResult;
		'\n    *[_type == "competitionPage"][0] {\n\t\t\tcontent\n\t\t}\n  ': CompetitionPageQueryResult;
		'\n    *[_type == "contactPage"][0] {\n\t\t\tsections[] {\n\t\t\t\t_key,\n\t\t\t\ttitle,\n\t\t\t\tdescription,\n\t\t\t\tcontacts[]-> {\n\t\t\t\t\t_id,\n\t\t\t\t\timage,\n\t\t\t\t\tname,\n\t\t\t\t\tpronouns,\n\t\t\t\t\temail,\n\t\t\t\t\t"titles": *[_type == "board"] | order(year desc)[0].sections[].members[person._ref match ^._id].title\n\t\t\t\t}\n\t\t\t}\n\t\t}\n  ': ContactPageQueryResult;
		'\n\t\t*[_type == "news"] | order(date desc) {\n\t\t\t_id,\n\t\t\ttitle,\n\t\t\tslug,\n\t\t\tdate,\n\t\t\tcover,\n\t\t}\n  ': NewsPageQueryResult;
		'\n   \t*[_type == "news" && slug.current == $slug][0] {\n\t\t\tcontent,\n\t\t\ttitle\n\t\t}\n  ': NewsStoryPageQueryResult;
		'\n    *[_type == "resource"] {\n      _id,\n      title,\n      description,\n      notes,\n      category,\n      link,\n      image {\n        asset->{\n          url\n        },\n        alt\n      },\n      tags\n    }\n  ': ResourcesQueryResult;
		'\n\t\t*[_type == "sponsor"] {\n\t\t\t_id,\n\t\t\tsince,\n\t\t\ttier,\n\t\t\tname,\n\t\t\tlogo {\n\t\t\t\tasset->{\n\t\t\t\t\turl\n\t\t\t\t},\n\t\t\t\talt\n\t\t\t},\n\t\t\tlogoDark {\n\t\t\t\tasset->{\n\t\t\t\t\turl\n\t\t\t\t}\n\t\t\t},\n\t\t\tnote\n\t\t}\n  ': SponsorQueryResult;
		'\n\t\t*[_type == "subteamsPage"][0] {\n\t\t\t_id,\n\t\t\tsubteams[] {\n\t\t\t\t_key,\n\t\t\t\tname,\n\t\t\t\tdescription\n\t\t\t}\n\t\t}\n  ': SubteamPageQueryResult;
	}
}
